language: node_js
node_js:
  - "7"

env:
  - DS_DB_HOST=localhost TASKEVO_DB_USER=travis TASKEVO_DB_PASS= TASKEVO_DB_NAME=taskevo TASKEVO_SERVER_NAME=localhost TASKEVO_SERVER_PROTOCOL=http

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE taskevo;'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cat src/sql/db.sql | mysql -h localhost -u travis taskevo
  - cat src/sql/data/*.sql | mysql -h localhost -u travis taskevo

script:
  - npm test

git:
  depth: 10
